/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/Chart/index.vue')['default']
    Drawer: typeof import('./src/components/Drawer/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Gituhub: typeof import('./src/components/Header/Gituhub.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    JsonView: typeof import('./src/components/Drawer/JsonView.vue')['default']
    Link: typeof import('./src/components/Header/Link.vue')['default']
  }
}
